// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common/pb/xendorser.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	xldgpb "github.com/xuperchain/xupercore/bcs/ledger/xledger/xldgpb"
	protos "github.com/xuperchain/xupercore/protos"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 请求参数
type EndorserRequest struct {
	Header               *Header             `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	RequestName          string              `protobuf:"bytes,2,opt,name=RequestName,proto3" json:"RequestName,omitempty"`
	BcName               string              `protobuf:"bytes,3,opt,name=BcName,proto3" json:"BcName,omitempty"`
	Fee                  *xldgpb.Transaction `protobuf:"bytes,4,opt,name=Fee,proto3" json:"Fee,omitempty"`
	RequestData          []byte              `protobuf:"bytes,5,opt,name=RequestData,proto3" json:"RequestData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *EndorserRequest) Reset()         { *m = EndorserRequest{} }
func (m *EndorserRequest) String() string { return proto.CompactTextString(m) }
func (*EndorserRequest) ProtoMessage()    {}
func (*EndorserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_febb5bdd4c8870e5, []int{0}
}

func (m *EndorserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EndorserRequest.Unmarshal(m, b)
}
func (m *EndorserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EndorserRequest.Marshal(b, m, deterministic)
}
func (m *EndorserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EndorserRequest.Merge(m, src)
}
func (m *EndorserRequest) XXX_Size() int {
	return xxx_messageInfo_EndorserRequest.Size(m)
}
func (m *EndorserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EndorserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EndorserRequest proto.InternalMessageInfo

func (m *EndorserRequest) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *EndorserRequest) GetRequestName() string {
	if m != nil {
		return m.RequestName
	}
	return ""
}

func (m *EndorserRequest) GetBcName() string {
	if m != nil {
		return m.BcName
	}
	return ""
}

func (m *EndorserRequest) GetFee() *xldgpb.Transaction {
	if m != nil {
		return m.Fee
	}
	return nil
}

func (m *EndorserRequest) GetRequestData() []byte {
	if m != nil {
		return m.RequestData
	}
	return nil
}

type EndorserResponse struct {
	Header               *Header               `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	ResponseName         string                `protobuf:"bytes,2,opt,name=ResponseName,proto3" json:"ResponseName,omitempty"`
	EndorserAddress      string                `protobuf:"bytes,3,opt,name=EndorserAddress,proto3" json:"EndorserAddress,omitempty"`
	EndorserSign         *protos.SignatureInfo `protobuf:"bytes,4,opt,name=EndorserSign,proto3" json:"EndorserSign,omitempty"`
	ResponseData         []byte                `protobuf:"bytes,5,opt,name=ResponseData,proto3" json:"ResponseData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *EndorserResponse) Reset()         { *m = EndorserResponse{} }
func (m *EndorserResponse) String() string { return proto.CompactTextString(m) }
func (*EndorserResponse) ProtoMessage()    {}
func (*EndorserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_febb5bdd4c8870e5, []int{1}
}

func (m *EndorserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EndorserResponse.Unmarshal(m, b)
}
func (m *EndorserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EndorserResponse.Marshal(b, m, deterministic)
}
func (m *EndorserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EndorserResponse.Merge(m, src)
}
func (m *EndorserResponse) XXX_Size() int {
	return xxx_messageInfo_EndorserResponse.Size(m)
}
func (m *EndorserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EndorserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EndorserResponse proto.InternalMessageInfo

func (m *EndorserResponse) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *EndorserResponse) GetResponseName() string {
	if m != nil {
		return m.ResponseName
	}
	return ""
}

func (m *EndorserResponse) GetEndorserAddress() string {
	if m != nil {
		return m.EndorserAddress
	}
	return ""
}

func (m *EndorserResponse) GetEndorserSign() *protos.SignatureInfo {
	if m != nil {
		return m.EndorserSign
	}
	return nil
}

func (m *EndorserResponse) GetResponseData() []byte {
	if m != nil {
		return m.ResponseData
	}
	return nil
}

func init() {
	proto.RegisterType((*EndorserRequest)(nil), "pb.EndorserRequest")
	proto.RegisterType((*EndorserResponse)(nil), "pb.EndorserResponse")
}

func init() { proto.RegisterFile("common/pb/xendorser.proto", fileDescriptor_febb5bdd4c8870e5) }

var fileDescriptor_febb5bdd4c8870e5 = []byte{
	// 395 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x4f, 0x4e, 0xe3, 0x30,
	0x14, 0xc6, 0x95, 0x76, 0xa6, 0x52, 0xdd, 0x4a, 0x53, 0xb9, 0xd3, 0x51, 0xa6, 0xdd, 0x64, 0x22,
	0x8d, 0x14, 0xb1, 0x88, 0xd5, 0xb2, 0x2a, 0x3b, 0xca, 0x1f, 0xc1, 0x86, 0x45, 0x40, 0x2c, 0xd8,
	0x39, 0xce, 0x23, 0x44, 0x4a, 0x6c, 0x63, 0xa7, 0xa8, 0x6b, 0xae, 0xc0, 0x65, 0xb8, 0x07, 0x47,
	0x80, 0x83, 0xa0, 0x24, 0x6e, 0x93, 0x94, 0x0d, 0xab, 0xd6, 0xbf, 0xf7, 0xbd, 0xf7, 0xbe, 0xcf,
	0x31, 0xfa, 0xcb, 0x44, 0x96, 0x09, 0x4e, 0x64, 0x48, 0x36, 0xc0, 0x23, 0xa1, 0x34, 0x28, 0x5f,
	0x2a, 0x91, 0x0b, 0xdc, 0x91, 0xe1, 0xf4, 0xdf, 0x66, 0x2d, 0x41, 0x31, 0xa1, 0x80, 0x94, 0x50,
	0x13, 0x09, 0x2a, 0x4b, 0xb4, 0x4e, 0x04, 0xaf, 0x64, 0xd3, 0x79, 0x2d, 0x09, 0x99, 0x26, 0x29,
	0x44, 0x31, 0x28, 0xb2, 0xd9, 0xfd, 0x46, 0x71, 0x31, 0xbb, 0x3a, 0x9a, 0x96, 0x65, 0xd9, 0x22,
	0x34, 0xa9, 0x97, 0xc7, 0x42, 0xc4, 0x29, 0x50, 0x99, 0x68, 0xf3, 0x97, 0x50, 0x99, 0x10, 0xca,
	0xb9, 0xc8, 0x69, 0x9e, 0x08, 0xae, 0x4d, 0xeb, 0xec, 0x6b, 0xab, 0x92, 0xac, 0x2a, 0xba, 0xaf,
	0x16, 0xfa, 0x75, 0x66, 0x42, 0x04, 0xf0, 0xb8, 0x06, 0x9d, 0x63, 0x17, 0xf5, 0x1e, 0x80, 0x46,
	0xa0, 0x6c, 0xcb, 0xb1, 0xbc, 0xc1, 0x02, 0xf9, 0x32, 0xf4, 0x2f, 0x4a, 0x12, 0x98, 0x0a, 0x76,
	0xd0, 0xc0, 0xc8, 0xaf, 0x68, 0x06, 0x76, 0xc7, 0xb1, 0xbc, 0x7e, 0xd0, 0x44, 0xf8, 0x0f, 0xea,
	0xad, 0x58, 0x59, 0xec, 0x96, 0x45, 0x73, 0xc2, 0xff, 0x51, 0xf7, 0x1c, 0xc0, 0xfe, 0x51, 0x8e,
	0x1e, 0xfb, 0x55, 0x5a, 0xff, 0x46, 0x51, 0xae, 0x29, 0x2b, 0x7c, 0x07, 0x45, 0xbd, 0xb1, 0xe0,
	0x94, 0xe6, 0xd4, 0xfe, 0xe9, 0x58, 0xde, 0x30, 0x68, 0x22, 0xf7, 0xdd, 0x42, 0xa3, 0xda, 0xba,
	0x96, 0x82, 0x6b, 0xf8, 0x96, 0x77, 0x17, 0x0d, 0xb7, 0xfa, 0x86, 0xf9, 0x16, 0xc3, 0x5e, 0x7d,
	0x2d, 0xc7, 0x51, 0xa4, 0x40, 0x6b, 0x13, 0x63, 0x1f, 0xe3, 0x25, 0x1a, 0x6e, 0xd1, 0x75, 0x12,
	0x73, 0x13, 0x6c, 0x52, 0xdd, 0xaf, 0xf6, 0x0b, 0x46, 0xf3, 0xb5, 0x82, 0x4b, 0x7e, 0x2f, 0x82,
	0x96, 0xb4, 0x69, 0xa4, 0x11, 0xb2, 0xc5, 0x16, 0x0c, 0xf5, 0x77, 0xaf, 0x0c, 0xdf, 0xd6, 0xbb,
	0x4e, 0x68, 0x9a, 0xe2, 0x71, 0x91, 0x6e, 0xef, 0xf3, 0x4d, 0x7f, 0xb7, 0x61, 0x35, 0xcb, 0x9d,
	0x3d, 0xbf, 0x7d, 0xbc, 0x74, 0x26, 0xee, 0x88, 0x3c, 0xcd, 0xc9, 0x76, 0x20, 0xa3, 0x69, 0x7a,
	0x64, 0x1d, 0xac, 0x06, 0x77, 0xfd, 0xdd, 0xe3, 0x08, 0x7b, 0xa5, 0xf3, 0xc3, 0xcf, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x7e, 0xa1, 0x96, 0x28, 0xe8, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// XendorserClient is the client API for Xendorser service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type XendorserClient interface {
	EndorserCall(ctx context.Context, in *EndorserRequest, opts ...grpc.CallOption) (*EndorserResponse, error)
}

type xendorserClient struct {
	cc grpc.ClientConnInterface
}

func NewXendorserClient(cc grpc.ClientConnInterface) XendorserClient {
	return &xendorserClient{cc}
}

func (c *xendorserClient) EndorserCall(ctx context.Context, in *EndorserRequest, opts ...grpc.CallOption) (*EndorserResponse, error) {
	out := new(EndorserResponse)
	err := c.cc.Invoke(ctx, "/pb.xendorser/EndorserCall", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// XendorserServer is the server API for Xendorser service.
type XendorserServer interface {
	EndorserCall(context.Context, *EndorserRequest) (*EndorserResponse, error)
}

// UnimplementedXendorserServer can be embedded to have forward compatible implementations.
type UnimplementedXendorserServer struct {
}

func (*UnimplementedXendorserServer) EndorserCall(ctx context.Context, req *EndorserRequest) (*EndorserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EndorserCall not implemented")
}

func RegisterXendorserServer(s *grpc.Server, srv XendorserServer) {
	s.RegisterService(&_Xendorser_serviceDesc, srv)
}

func _Xendorser_EndorserCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndorserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XendorserServer).EndorserCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.xendorser/EndorserCall",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XendorserServer).EndorserCall(ctx, req.(*EndorserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Xendorser_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.xendorser",
	HandlerType: (*XendorserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EndorserCall",
			Handler:    _Xendorser_EndorserCall_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "common/pb/xendorser.proto",
}
