// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.5.1
// source: xuperos.proto

package pb

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type XuperOSErrNo int32

const (
	XuperOSErrNo_SUCCESS XuperOSErrNo = 0
	// 内部错误
	XuperOSErrNo_INTERNAL_ERROR XuperOSErrNo = 1
	// 参数错误
	XuperOSErrNo_PARAM_ERROR XuperOSErrNo = 2
	// 未知错误
	XuperOSErrNo_UNKNOW_ERROR XuperOSErrNo = 3
)

// Enum value maps for XuperOSErrNo.
var (
	XuperOSErrNo_name = map[int32]string{
		0: "SUCCESS",
		1: "INTERNAL_ERROR",
		2: "PARAM_ERROR",
		3: "UNKNOW_ERROR",
	}
	XuperOSErrNo_value = map[string]int32{
		"SUCCESS":        0,
		"INTERNAL_ERROR": 1,
		"PARAM_ERROR":    2,
		"UNKNOW_ERROR":   3,
	}
)

func (x XuperOSErrNo) Enum() *XuperOSErrNo {
	p := new(XuperOSErrNo)
	*p = x
	return p
}

func (x XuperOSErrNo) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (XuperOSErrNo) Descriptor() protoreflect.EnumDescriptor {
	return file_xuperos_proto_enumTypes[0].Descriptor()
}

func (XuperOSErrNo) Type() protoreflect.EnumType {
	return &file_xuperos_proto_enumTypes[0]
}

func (x XuperOSErrNo) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use XuperOSErrNo.Descriptor instead.
func (XuperOSErrNo) EnumDescriptor() ([]byte, []int) {
	return file_xuperos_proto_rawDescGZIP(), []int{0}
}

// 通用请求Header
type ReqHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 请求id
	LogId string `protobuf:"bytes,1,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`
	// 标记请求方，方便问题定位
	SelfName string `protobuf:"bytes,2,opt,name=self_name,json=selfName,proto3" json:"self_name,omitempty"`
}

func (x *ReqHeader) Reset() {
	*x = ReqHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xuperos_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqHeader) ProtoMessage() {}

func (x *ReqHeader) ProtoReflect() protoreflect.Message {
	mi := &file_xuperos_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqHeader.ProtoReflect.Descriptor instead.
func (*ReqHeader) Descriptor() ([]byte, []int) {
	return file_xuperos_proto_rawDescGZIP(), []int{0}
}

func (x *ReqHeader) GetLogId() string {
	if x != nil {
		return x.LogId
	}
	return ""
}

func (x *ReqHeader) GetSelfName() string {
	if x != nil {
		return x.SelfName
	}
	return ""
}

// 通用响应Header
type RespHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 请求id
	LogId string `protobuf:"bytes,1,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`
	// 错误码
	Error XuperOSErrNo `protobuf:"varint,2,opt,name=error,proto3,enum=pb.XuperOSErrNo" json:"error,omitempty"`
	// 节点追踪信息，方便问题定位
	TraceId string `protobuf:"bytes,3,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
}

func (x *RespHeader) Reset() {
	*x = RespHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xuperos_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespHeader) ProtoMessage() {}

func (x *RespHeader) ProtoReflect() protoreflect.Message {
	mi := &file_xuperos_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespHeader.ProtoReflect.Descriptor instead.
func (*RespHeader) Descriptor() ([]byte, []int) {
	return file_xuperos_proto_rawDescGZIP(), []int{1}
}

func (x *RespHeader) GetLogId() string {
	if x != nil {
		return x.LogId
	}
	return ""
}

func (x *RespHeader) GetError() XuperOSErrNo {
	if x != nil {
		return x.Error
	}
	return XuperOSErrNo_SUCCESS
}

func (x *RespHeader) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type BaseReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *ReqHeader `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`
}

func (x *BaseReq) Reset() {
	*x = BaseReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xuperos_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BaseReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseReq) ProtoMessage() {}

func (x *BaseReq) ProtoReflect() protoreflect.Message {
	mi := &file_xuperos_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseReq.ProtoReflect.Descriptor instead.
func (*BaseReq) Descriptor() ([]byte, []int) {
	return file_xuperos_proto_rawDescGZIP(), []int{2}
}

func (x *BaseReq) GetHeader() *ReqHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

type BaseResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *RespHeader `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`
}

func (x *BaseResp) Reset() {
	*x = BaseResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xuperos_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BaseResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResp) ProtoMessage() {}

func (x *BaseResp) ProtoReflect() protoreflect.Message {
	mi := &file_xuperos_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResp.ProtoReflect.Descriptor instead.
func (*BaseResp) Descriptor() ([]byte, []int) {
	return file_xuperos_proto_rawDescGZIP(), []int{3}
}

func (x *BaseResp) GetHeader() *RespHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

var File_xuperos_proto protoreflect.FileDescriptor

var file_xuperos_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x78, 0x75, 0x70, 0x65, 0x72, 0x6f, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x02, 0x70, 0x62, 0x22, 0x3f, 0x0a, 0x09, 0x52, 0x65, 0x71, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x12, 0x15, 0x0a, 0x06, 0x6c, 0x6f, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x6c, 0x6f, 0x67, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x6c, 0x66, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x6c, 0x66,
	0x4e, 0x61, 0x6d, 0x65, 0x22, 0x66, 0x0a, 0x0a, 0x52, 0x65, 0x73, 0x70, 0x48, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x12, 0x15, 0x0a, 0x06, 0x6c, 0x6f, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x58, 0x75,
	0x70, 0x65, 0x72, 0x4f, 0x53, 0x45, 0x72, 0x72, 0x4e, 0x6f, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x72, 0x61, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x72, 0x61, 0x63, 0x65, 0x49, 0x64, 0x22, 0x30, 0x0a, 0x07,
	0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x12, 0x25, 0x0a, 0x06, 0x48, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71,
	0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x22, 0x32,
	0x0a, 0x08, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x26, 0x0a, 0x06, 0x48, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e,
	0x52, 0x65, 0x73, 0x70, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x48, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x2a, 0x52, 0x0a, 0x0c, 0x58, 0x75, 0x70, 0x65, 0x72, 0x4f, 0x53, 0x45, 0x72, 0x72,
	0x4e, 0x6f, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x00, 0x12,
	0x12, 0x0a, 0x0e, 0x49, 0x4e, 0x54, 0x45, 0x52, 0x4e, 0x41, 0x4c, 0x5f, 0x45, 0x52, 0x52, 0x4f,
	0x52, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x50, 0x41, 0x52, 0x41, 0x4d, 0x5f, 0x45, 0x52, 0x52,
	0x4f, 0x52, 0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x5f, 0x45,
	0x52, 0x52, 0x4f, 0x52, 0x10, 0x03, 0x32, 0x34, 0x0a, 0x07, 0x58, 0x75, 0x70, 0x65, 0x72, 0x4f,
	0x53, 0x12, 0x29, 0x0a, 0x0a, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x12,
	0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x0c, 0x2e, 0x70,
	0x62, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_xuperos_proto_rawDescOnce sync.Once
	file_xuperos_proto_rawDescData = file_xuperos_proto_rawDesc
)

func file_xuperos_proto_rawDescGZIP() []byte {
	file_xuperos_proto_rawDescOnce.Do(func() {
		file_xuperos_proto_rawDescData = protoimpl.X.CompressGZIP(file_xuperos_proto_rawDescData)
	})
	return file_xuperos_proto_rawDescData
}

var file_xuperos_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_xuperos_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_xuperos_proto_goTypes = []interface{}{
	(XuperOSErrNo)(0),  // 0: pb.XuperOSErrNo
	(*ReqHeader)(nil),  // 1: pb.ReqHeader
	(*RespHeader)(nil), // 2: pb.RespHeader
	(*BaseReq)(nil),    // 3: pb.BaseReq
	(*BaseResp)(nil),   // 4: pb.BaseResp
}
var file_xuperos_proto_depIdxs = []int32{
	0, // 0: pb.RespHeader.error:type_name -> pb.XuperOSErrNo
	1, // 1: pb.BaseReq.Header:type_name -> pb.ReqHeader
	2, // 2: pb.BaseResp.Header:type_name -> pb.RespHeader
	3, // 3: pb.XuperOS.CheckAlive:input_type -> pb.BaseReq
	4, // 4: pb.XuperOS.CheckAlive:output_type -> pb.BaseResp
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_xuperos_proto_init() }
func file_xuperos_proto_init() {
	if File_xuperos_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_xuperos_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xuperos_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xuperos_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BaseReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xuperos_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BaseResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_xuperos_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_xuperos_proto_goTypes,
		DependencyIndexes: file_xuperos_proto_depIdxs,
		EnumInfos:         file_xuperos_proto_enumTypes,
		MessageInfos:      file_xuperos_proto_msgTypes,
	}.Build()
	File_xuperos_proto = out.File
	file_xuperos_proto_rawDesc = nil
	file_xuperos_proto_goTypes = nil
	file_xuperos_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// XuperOSClient is the client API for XuperOS service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type XuperOSClient interface {
	// 示例接口
	CheckAlive(ctx context.Context, in *BaseReq, opts ...grpc.CallOption) (*BaseResp, error)
}

type xuperOSClient struct {
	cc grpc.ClientConnInterface
}

func NewXuperOSClient(cc grpc.ClientConnInterface) XuperOSClient {
	return &xuperOSClient{cc}
}

func (c *xuperOSClient) CheckAlive(ctx context.Context, in *BaseReq, opts ...grpc.CallOption) (*BaseResp, error) {
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, "/pb.XuperOS/CheckAlive", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// XuperOSServer is the server API for XuperOS service.
type XuperOSServer interface {
	// 示例接口
	CheckAlive(context.Context, *BaseReq) (*BaseResp, error)
}

// UnimplementedXuperOSServer can be embedded to have forward compatible implementations.
type UnimplementedXuperOSServer struct {
}

func (*UnimplementedXuperOSServer) CheckAlive(context.Context, *BaseReq) (*BaseResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckAlive not implemented")
}

func RegisterXuperOSServer(s *grpc.Server, srv XuperOSServer) {
	s.RegisterService(&_XuperOS_serviceDesc, srv)
}

func _XuperOS_CheckAlive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BaseReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XuperOSServer).CheckAlive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.XuperOS/CheckAlive",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XuperOSServer).CheckAlive(ctx, req.(*BaseReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _XuperOS_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.XuperOS",
	HandlerType: (*XuperOSServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckAlive",
			Handler:    _XuperOS_CheckAlive_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "xuperos.proto",
}
